# Generated by Django 4.1.7 on 2023-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="model_detail",
            field=models.CharField(default="该用户没有输入任何描述哦~", max_length=200),
        ),
    ]
