# Generated by Django 4.1.7 on 2023-03-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0002_model_model_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="model_picture",
            field=models.CharField(
                default="https://dummyimage.com/400X400", max_length=500
            ),
        ),
    ]
