# Generated by Django 4.1.7 on 2023-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0004_alter_model_model_name_alter_model_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="update_method",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
