# Generated by Django 4.1.7 on 2023-04-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0005_model_update_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="update_method",
            field=models.IntegerField(default=0),
        ),
    ]
