# Generated by Django 4.2 on 2023-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0007_model_model_riskmain_model_model_riskmethods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="model_riskstatus",
            field=models.IntegerField(default=0),
        ),
    ]
