# Generated by Django 4.2 on 2023-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0009_model_model_risklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="model_riskmethods",
            field=models.CharField(default="暂无相应方法", max_length=10000),
        ),
    ]
