# Generated by Django 4.1.7 on 2023-04-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background_photo",
            field=models.CharField(
                default="https://dummyimage.com/400X400", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="head_photo",
            field=models.CharField(
                default="https://dummyimage.com/400X400", max_length=500
            ),
        ),
    ]
